server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: 4518
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: HOTEL-SERVICE
  config:
    import: "optional:configserver:http://localhost:8085"
